# Site settings
title: Edwin D. de Jong
#email: see contact info
#description: description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://edwin-de-jong.github.io/" 
twitter_username: EdwinDdeJong
github_username:  edwin-de-jong

# Build settings
markdown: kramdown
theme: gravity